# Aldxdeveloper Docker Setup
version: "3.8"

networks:
  ubuntu:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./logs:/var/log/nginx
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - ubuntu

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: php
    restart: always
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - ubuntu

  mysql:
    build:
      context: .
      dockerfile: ./.docker/mysql/Dockerfile
    image: mariadb:10.3
    container_name: mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - ubuntu

  phpmyadmin:
    build:
      context: .
      dockerfile: ./.docker/mysql/phpmyadmin/Dockerfile
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 2000000000000
    depends_on:
      - mysql
    ports:
      - "81:80"
    networks:
      - ubuntu

  composer:
    build:
      context: .
      dockerfile: ./.docker/php/composer/Dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: ubuntu
    networks:
      - ubuntu
    entrypoint: [ "composer", "--ignore-platform-reqs" ]

  npm:
    image: node:18-alpine
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "npm" ]